[menuconfig] Add export as standalone distributive
 - Add checking validity of deployment
 - Refactor menu layout

diff --git a/bin/menuconfig b/bin/menuconfig
--- a/bin/menuconfig
+++ b/bin/menuconfig
@@ -6,6 +6,7 @@ cd $BASEDIR
 DEPLOYS_DIR=deploys
 DEPLOY_ACTIVE_LINK=deploy-active
 SERVICES_AVAILABLE_DIR=services-available
+STANDALONE_DIR=exports
 
 ################################
 msg() {
@@ -14,6 +15,7 @@ msg() {
     case "$TYPE" in
         warn) printf "WARNING: %s\n" "$*" >&2 ;;
         err)  printf "ERROR: %s\n" "$*" >&2 ;;
+        null) ;;
         *)    printf "%s\n" "$*" ;;
     esac
 }
@@ -39,8 +41,47 @@ check_consistency() {
     # TODO: check is link deploys/localhost/Makefile to ../../mk/deploys-template.mk
     # if not, check if there is string 'include ../../mk/deploys-template.mk'
 
-    # TODO: check .env file in deployments
     true
+}
+
+deploy_is_valid() {
+    DIR="$1"
+    MSG_TYPE="${2:-err}"
+
+    if ! ls $DIR/*.yaml 2> /dev/null >&2; then
+        msg $MSG_TYPE "There is no $DIR/*.yaml"
+        return 1
+    fi
+
+    if ! ls $DIR/*.yaml | grep -qv '\.override.yaml' > /dev/null; then
+        msg $MSG_TYPE "There is only $DIR/*.override.yaml. Need at least one not override.yaml"
+        return 1
+    fi
+
+    if [ ! -e $DIR/.env ]; then
+        msg $MSG_TYPE "There is no $DIR/.env"
+        return 1
+    fi
+
+    if ls $DIR/*.yml 2> /dev/null >&2; then
+        msg $MSG_TYPE "There is no $DIR/*.yml files. Please rename or move out them from deployment"
+        return 1
+    fi
+
+    for YAML in $DIR/*.yaml; do
+        if [ -L $YAML ]; then
+            FILE=$(readlink $YAML)
+            if [ "$(basename $FILE)" != "$(basename $YAML)" ]; then
+                TEST_FAIL=true
+                msg $MSG_TYPE "Link $YAML point to file $FILE with different name"
+            fi
+        fi
+    done
+
+    if [ -n "$TEST_FAIL" ]; then
+        unset TEST_FAIL
+        return 1
+    fi
 }
 
 get_deploys_list() {
@@ -98,7 +139,7 @@ gen_menu_items() {
             eval ADDITIONAL_INFO="\"\$($FUNC_ADDITIONAL_INFO$ITEM)\""
         fi
 
-        PROMPT="${PROMPT}$(printf "%2d) %-25s [ %s ]" ${MENU_INDEX} "$ITEM" "$ADDITIONAL_INFO")\n"
+        PROMPT="${PROMPT}$(printf "%2d) %-27s [ %s ]" ${MENU_INDEX} "$ITEM" "$ADDITIONAL_INFO")\n"
         eval MENU_ITEM_${VAR_NAME}_$MENU_INDEX="\$ITEM"
     done
     PROMPT="${PROMPT}\n"
@@ -182,19 +223,97 @@ get_deploy_status() {
     unset SERVICES
 }
 
-######################################################################
-menu_show_active_deployment() {
-    echo "=============================================================================="
-    if [ ! -L $DEPLOY_ACTIVE_LINK ]; then
-        msg warn "No active deployment"
-        msg warn ""
+make_docker_compose_yaml() {
+    DIR_IN="$(readlink $1)"
+    FILE_OUT="$2/docker-compose.yaml"
+
+    SEP='###########################'
+
+    unset FIRST
+
+    for YAML in $DIR_IN/*.yaml; do
+        case $1 in
+            *.override.yaml) ;;
+            *)
+                if [ -L $YAML ]; then
+                    YAML_REAL=$(readlink $YAML)
+                fi
+                if [ -z "$FIRST" ]; then
+                    FIRST=1
+                    printf "$SEP$SEP$SEP\n" > $FILE_OUT
+                    printf "# File automatically generated by BeFAIR (https://github.com/CoronaWhy/befair)\n#\n" >> $FILE_OUT
+                    printf "# Deployments \"$DIR_IN\" as standalone distributives\n" >> $FILE_OUT
+                    printf "$SEP$SEP$SEP\n\n" >> $FILE_OUT
+                    printf "\n$SEP %-30s $SEP\n\n" $YAML_REAL >> $FILE_OUT
+                    cat $YAML             >> $FILE_OUT
+                else
+                    printf "\n$SEP %-30s $SEP\n\n" $YAML_REAL >> $FILE_OUT
+                    sed -e '/^version:/d; /^services:/d' $YAML >> $FILE_OUT
+                fi
+            ;;
+        esac
+    done
+
+}
+
+export_standalone_distributive() {
+    DEPLOY_DIR=$(readlink $1)
+    DEPLOY_NAME=$(basename $DEPLOY_DIR)
+    DEPLOY_STANDALONE_DIR=$STANDALONE_DIR/$DEPLOY_NAME
+
+    if ! deploy_is_valid $DEPLOY_DIR err; then
+        msg err "Exporting "$DEPLOY_NAME" fail"
         return
     fi
-    if [ ! -e $DEPLOY_ACTIVE_LINK/.env ]; then
-        msg warn "There is no .env"
+
+    if [ -d $DEPLOY_STANDALONE_DIR ]; then
+        if ask_yes "Directory $DEPLOY_STANDALONE_DIR exist, do you want remove it before export?"; then
+            rm -r $DEPLOY_STANDALONE_DIR
+        fi
+    fi
+    mkdir -p $STANDALONE_DIR/$DEPLOY_NAME
+
+    make_docker_compose_yaml $DEPLOY_ACTIVE_LINK $DEPLOY_STANDALONE_DIR
+
+    cp mk/standalone-template.mk $DEPLOY_STANDALONE_DIR/Makefile
+    if ! useremail=dummy traefikhost=dummy COMPOSE_FILE=$DEPLOY_STANDALONE_DIR/docker-compose.yaml docker-compose config -q; then
+        msg norm "$MENU_HR"
+        msg err  "Export to $DEPLOY_STANDALONE_DIR/docker-compose.yaml fail"
+        msg norm ""
+        msg tips "Checkout this generated docker-compose.yaml for errors:"
+        msg tips "\$ cd $DEPLOY_STANDALONE_DIR"
+        msg tips "\$ make check"
+        return
+    fi
+
+    cp $DEPLOY_DIR/.env* $DEPLOY_STANDALONE_DIR/ 2> /dev/null || true
+    cp $DEPLOY_DIR/*.override.yaml $DEPLOY_STANDALONE_DIR/ 2> /dev/null || true
+
+    # TODO: copy volumes(?) and secrets
+
+    msg info "Active project exported to $DEPLOY_STANDALONE_DIR/"
+    msg info ""
+    msg tips "You can make tar.gz by:"
+    msg tips "\$ cd $DEPLOY_STANDALONE_DIR"
+    msg tips "\$ make tgz"
+}
+
+############################################################################################
+MENU_HR="==================================================================================="
+
+menu_show_active_deployment() {
+    msg norm $MENU_HR
+    if [ ! -L $DEPLOY_ACTIVE_LINK ]; then
+        msg warn "No active deployment"
+        msg norm $MENU_HR
+        return
     fi
 
     DEPLOY_ACTIVE=$(basename $(readlink $DEPLOY_ACTIVE_LINK))
+    if ! deploy_is_valid $DEPLOYS_DIR/$DEPLOY_ACTIVE warn; then
+        msg norm $MENU_HR
+    fi
+
     echo -n "Active deployment is \"$DEPLOY_ACTIVE\". "
 
     SERVICES_ACTIVE=$(get_services_active_list $DEPLOY_ACTIVE_LINK)
@@ -217,7 +336,7 @@ menu_show_prompt() {
     fi
 
     case $MENU_MODE in
-        show-deploy-available)
+        choose-deploy-available)
             if [ -L $DEPLOY_ACTIVE_LINK ]; then
                 DEPLOYS=$(get_deploys_list $DEPLOYS_DIR)
 
@@ -232,14 +351,18 @@ menu_show_prompt() {
 
         create-deploy)
             COPY_DEPLOY="$(get_deploys_list $DEPLOYS_DIR)"
-            gen_menu_items "Available deployments. Choose deployment to make COPY of it:\n" COPY_DEPLOY
+            gen_menu_items "Available deployments. Choose deployment to make COPY of it:\n" \
+                           COPY_DEPLOY \
+                           "get_deploy_status $DEPLOYS_DIR/"
             PROMPT="${PROMPT} m) Make new deployment\n"
             PROMPT="${PROMPT} R) Remove deployment\n"
         ;;
 
         remove-deploy)
             REMOVE_DEPLOY="$(get_deploys_list $DEPLOYS_DIR)"
-            gen_menu_items "Available deployments. Choose deployment to REMOVE it:\n" REMOVE_DEPLOY
+            gen_menu_items "Available deployments. Choose deployment to REMOVE it:\n" \
+                           REMOVE_DEPLOY \
+                           "get_deploy_status $DEPLOYS_DIR/"
         ;;
 
         *)
@@ -248,24 +371,32 @@ menu_show_prompt() {
                 gen_menu_items "Available deployments. Choose deployment to make it active:\n" \
                                DEPLOYS \
                                "get_deploy_status $DEPLOYS_DIR/"
-            else
-                PROMPT="${PROMPT} l) List of available deployments to activate one\n"
             fi
         ;;
     esac
 
-    if [ "$MENU_MODE" != "create-deploy" ]; then
-        PROMPT="${PROMPT} c) Create new deployment\n"
-    fi
-
-    if [ "$MENU_MODE" != "remove-deploy" ]; then
-        PROMPT="${PROMPT} R) Remove deployment\n"
-    fi
-
     if [ -L $DEPLOY_ACTIVE_LINK ]; then
         PROMPT="${PROMPT} d) Disable current deployment\n"
         PROMPT="${PROMPT} r) Rename current deployment\n"
+        if deploy_is_valid $DEPLOYS_DIR/$DEPLOY_ACTIVE null; then
+            PROMPT="${PROMPT}\n e) Export from current deployment to standalone distributive docker-compose.yaml\n"
+        fi
+        PROMPT="${PROMPT}\n"
     fi
+
+    PROMPT="${PROMPT}$MENU_HR\n\n"
+    if [ -L $DEPLOY_ACTIVE_LINK ]; then
+        PROMPT="${PROMPT} c) Choose available deployment [ mode ]\n"
+    fi
+    if [ "$MENU_MODE" != "create-deploy" ]; then
+        PROMPT="${PROMPT} C) Create new deployment       [ mode ]\n"
+    fi
+
+    if [ "$MENU_MODE" != "remove-deploy" ]; then
+        PROMPT="${PROMPT} R) Remove deployment           [ mode ]\n"
+    fi
+
+    PROMPT="${PROMPT}\n Enter) Refresh screen or quit from mode\n"
     PROMPT="${PROMPT} q) Quit\n\nChoose> "
     unset MENU_MODE
 
@@ -344,10 +475,10 @@ menu_main() {
         clear
 
         case $ANS in
-            [0-9]*) menu_numeric_index_action       ;;
-            l)      MENU_MODE=show-deploy-available ;;
-            c)      MENU_MODE=create-deploy         ;;
-            R)      MENU_MODE=remove-deploy         ;;
+            [0-9]*) menu_numeric_index_action         ;;
+            c)      MENU_MODE=choose-deploy-available ;;
+            C)      MENU_MODE=create-deploy           ;;
+            R)      MENU_MODE=remove-deploy           ;;
             m)
                 ask_deploy_name DEPLOY_NEW new
                 if [ -n "$DEPLOY_NEW" ]; then
@@ -369,6 +500,9 @@ menu_main() {
             d)
                 [ -L $DEPLOY_ACTIVE_LINK ] && rm $DEPLOY_ACTIVE_LINK
                 msg info "Active deployment \"$DEPLOY_ACTIVE\" disabled."
+            ;;
+            e)
+                export_standalone_distributive $DEPLOY_ACTIVE_LINK
             ;;
 
             q) exit ;;
